### ISSUE TITLE
Do not require dependecy on `thiserror` from users

### ISSUE THREAD

**Issue by jalil-salame** [shakacode/justerror#4]
In order to use this library you need to aditionally specify a dependecy on `thiserror` in your `Cargo.toml`:

```rust
use justerror::Error;

#[Error]
enum MyError {
    Foo,
    Bar,
}
```

```toml
[package]
name = "test"
version = "0.1.0"
edition = "2021"

[dependencies]
justerror = "1"
# thiserror = "1" # uncomment this line
```

Without specifying the dependecy on `thiserror`, compilation fails. This is not documented and is slightly annoying to do.
